<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);DOCK_REACTIVEUI_REACTIVE</DefineConstants>
    <PackageId>Dock.Model.ReactiveUI.Services.Reactive</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsDocFx)' == 'true'">
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <!--<Import Project="..\..\build\SignAssembly.props" />-->
  <Import Project="..\..\build\SourceLink.props" />
  <Import Project="..\..\build\ReferenceAssemblies.props" />
  <Import Project="..\..\build\Microsoft.Extensions.DependencyInjection.props" />
  <Import Project="..\..\build\ReactiveUI.props" />

  <ItemGroup>
    <Compile Include="..\Dock.Model.ReactiveUI.Services\**\*.cs"
             Exclude="..\Dock.Model.ReactiveUI.Services\bin\**;..\Dock.Model.ReactiveUI.Services\obj\**"
             LinkBase="Shared" />
    <ProjectReference Include="..\Dock.Model\Dock.Model.csproj" />
    <ProjectReference Include="..\Dock.Model.ReactiveUI.Reactive\Dock.Model.ReactiveUI.Reactive.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
